[package]
name = "braker"
version = "0.1.0"
authors = ["Harry Rose"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.1"

[lib]
name = "braker"
crate-type = ["cdylib"]